#! /bin/sh
set -e

if [ -e /usr/share/ubiquity/license/run.sh ];then
	chmod 755 /usr/share/ubiquity/license/run.sh
fi

if [ -e /usr/bin/kylin_checkpasswd ];then
	chmod 755 /usr/bin/kylin_checkpasswd
fi

exit 0
